### ISSUE TITLE
Release of version 1.0

### ISSUE THREAD

**Issue by JimBacon** [rob-murray/os-leaflet#10]
Leaflet 1.0 has been released (see https://github.com/Leaflet/Leaflet/blob/master/CHANGELOG.md) so the way is clear to release os-leaflet 1.0.

**Comment by rob-murray** [comment]
Hi,
Thanks for reminding me ;)

I have a PR - #9 - that was waiting for Proj4Leaflet to be released with Leaflet 1.0 support - looks like this has happened now so I will update this project and release a new version.

**Comment by rob-murray** [comment]
Will release 1.0 to npm shortly - will try to resolve #15 and #12 before doing so

**Comment by JimBacon** [comment]
If it helps, I could justify spending some work time on this and submit a pull-request for you to consider. Don't know if you'd rather do it your own way though.

**Comment by rob-murray** [comment]
Thanks, any help is appreciated. I'm happy either way but I don't have a massive amount of time to spend on this at the moment so I may be a bit sporadic with updates. I'm aiming to have this done within a couple of weeks - it's not a lot of work but just need the time.

- [ ] #15 - Easy to change to HTTPS
- [ ] #12 - TBC - (I'm putting together a list of things to do to make this library more compliant, it may never be "accepted" but if I can implement those point you mention then that would be a good start)

**Comment by rob-murray** [comment]
I'm going with what's on master now - just need to make a release note to note the change in API.

**Comment by JimBacon** [comment]
Hi. You might have this planned but I just saw that if you follow the instructions at https://unpkg.com/ you can publish to npm and hit #16 simultaneously.

**Comment by rob-murray** [comment]
👍 
Yep, v1.0 was pushed a couple of weeks ago. Closing 💥
