### ISSUE TITLE
Explanation of non-compliance with T&Cs

### ISSUE THREAD

**Issue by JimBacon** [rob-murray/os-leaflet#12]
It would be helpful if you could explain in what way this does not comply with the OS OpenSpace terms and conditions to help assess whether it can be made to comply. I note that the OS OpenSpace have demonstrated how to use an earlier version of this in a compliant fashion. 
https://www.ordnancesurvey.co.uk/forums/discussion/1001864/using-leafletjs-with-openspace

**Comment by JimBacon** [comment]
Their comment (2014-02-27) about by-passing the API key refers to an earlier version of your work. Obviously this would breach T&Cs but this is no longer relevant. They then demonstrate a solution (2014-12-03) based on your work which one can take for granted is acceptable. The two requirements are to insert your API key and your website URL which they name as authParams in the code. I can't see anything further than that is being done differently.

As an additional note, the [T&Cs](https://www.ordnancesurvey.co.uk/business-and-government/licensing/licences/os-openspace-developer-agreement.html) also require, amongst other things, 

- 4.6.1 A copy of the End User Terms of Use is made easily accessible to End Users through a hypertext link within the Application.
- 5.2 The appropriate acknowledgement is:
_© Crown copyright and database rights [year] Ordnance Survey_ for large window screens; and
 _© Crown copyright 2013. Terms of Use_ for small window screens of 320 pixels or less in width.
- 5.3  You must ensure that the OS OpenSpace logo to include ‘powered by OpenSpace’ is included in a conspicuous position in Your Application

These items could be incorporated in to this module, in an optional way that doesn't constrain developers, to make it easier to comply. Is that a good idea?

I think it would be worth reopening a dialogue with OS when we think the code is as good as we can get it. I'm grateful for your effort to date.

**Comment by rob-murray** [comment]
👍 

Yes, I agree with including those items after reading the Developer Agreement - I've done this now and it can all be disabled with `attributionControl: false` map option.

**Comment by JimBacon** [comment]
This is good. A small quibble is that you have linked to the Developer Agreement when what the user needs to see is the End User Terms which is in Schedule 2 of the Developer Agreement. If only OS had provided the End User Terms on a separate url it would be easy. 

I will merge your code with mine and send you a pull request to look at. It uses a pop up to show a copy of the End User Terms. It is not ideal as it means the terms are hard-coded in to the module. I'll be interested in your opinion.

**Comment by rob-murray** [comment]
Oops, thought I copied​ link correctly from a real OS Openspace map.

Yes please, PRs much appreciated.
