### ISSUE TITLE
Add host Url as parameter when creating tile layer

### ISSUE THREAD

**Issue by JimBacon** [rob-murray/os-leaflet#14]
When applying for an OSOpenSpace API key it is associated with a project url. It appears from the example provided by OS that this should be included as the URL parameter in the WMS request as part of the authentication process. Currently this is hard-coded as `URL: 'file:///'` which is allowed for testing purposes. It would be good to allow this to be overriden by a user-supplied value.

**Comment by JimBacon** [comment]
Relates to issue #12

**Comment by rob-murray** [comment]
Fixed on master now
