### ISSUE TITLE
https

### ISSUE THREAD

**Issue by saturdaywalkers** [rob-murray/os-leaflet#15]
Change the hardcoded OS tile url to '//openspace.ordnancesurvey.co.uk/osmapapi/ts', so it works with both http and https websites

**Comment by JimBacon** [comment]
I think this is important as browsers are moving towards a requirement for apps sending location information to run on https and they don't like pages that mix https and http. If the simple change suggested above is all it takes then +1 from me.

**Comment by rob-murray** [comment]
Same here, I think when I first did this OpenSpace HTTPS was only available on the Pro version
