### ISSUE TITLE
upload to a cdn

### ISSUE THREAD

**Issue by saturdaywalkers** [rob-murray/os-leaflet#16]
upload to a cdn,
eg https://cdnjs.com/ (then 'request a lib')

thanks
andrew

**Comment by JamesMilnerUK** [comment]
To kill two birds with one stone, could potentially publish to NPM which would in turn deploy to https://unpkg.com/

**Comment by saturdaywalkers** [comment]
`<script defer src="https://unpkg.com/os-leaflet@1.0.0/OSOpenSpace.js"></script>`

thanks, andrew
