### ISSUE TITLE
TypeError: b is undefined with leaflet 1.0 Beta

### ISSUE THREAD

**Issue by OldGreyCells** [rob-murray/os-leaflet#8]
When using leaflet 1.0 beta, the error "TypeError: b is undefined" is thrown from line 1516 in leaflet-src.js. This getProjectedBounds function expects to see a bounds object in (I think) the CRS.projection.

From the Leaflet 1.0 beta changelog for 'TileLayer API improvements':

"Improved tile wrapping and bounding logic in TileLayer to work transparently and completely depent [sic] on the CRS used; removed the need for TileLayer hacks when using custom projections."

If you need more info or testing etc, I'm happy to help, but this is likely slightly deeper than I've been able to understand so far...

**Comment by rob-murray** [comment]
Thanks for letting me know, I had not tested against that beta yet... I will have a look.

**Comment by OldGreyCells** [comment]
Thanks Rob. From my progress so far, it seems 1.0 beta expects the CRS to be extended from L.CRS[.earth?] - it expects properties & methods on the CRS class that are not defined in L.Proj.CRS.

**Comment by rob-murray** [comment]
Thanks, I will set up a branch to test against the 1.0-beta - feel free to fork, fix and PR if you want it sooner than i get round to it ;)

**Comment by OldGreyCells** [comment]
> feel free to fork, fix and PR if you want

Hehe - gotta love your sense of humour :) 

Will try, but possibly a misplaced understanding of my abilities!

**Comment by salomvary** [comment]
FYI this works with Leaflet 1.0 beta 2:
http://dominique92.github.io/MyLeaflet/github.com/Dominique92/Leaflet.Map.MultiVendors/examples/index-v1.0.html

(Despite the demo is broken due to api key/referrer mismatch, I managed to get it working using my own api key.)

**Comment by rob-murray** [comment]
Thanks @salomvary that looks promising & I will have a look soon.

**Comment by rob-murray** [comment]
Yeah that example using the new Leaflet v1.0 API worked great.

The **leaflet-1.0-beta** branch works now.

**Comment by rob-murray** [comment]
Master branch supports Leaflet 1.0 now
